service: otp-service-backend
frameworkVersion: "3"

plugins:
    - serverless-dotenv-plugin

provider:
    name: aws
    runtime: nodejs16.x
    region: ap-south-1

functions:
    api:
        handler: server.handler
        timeout: 180
        events:
            - httpApi: "*"
            - httpApi:
                  path: /{proxy+}
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
            - websocket:
                route: $default
